apiVersion: apps/v1
kind: Deployment
metadata:
  name: hifi-liquidator-deployment
  labels:
    app: hifi-liquidator
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hifi-liquidator
  template:
    metadata:
      labels:
        app: hifi-liquidator
    spec:
      containers:
        - name: hifi-liquidator
          args:
            - "--config"
            - "./config.json"
            - "--db-file"
            - "./db.json"
            - "--interval"
            - "15000"
            - "--min-profit"
            - "100"
            - "--url"
            - "$(NODE_URL)"
          env:
            - name: NODE_URL
              valueFrom:
                secretKeyRef:
                  key: node_url
                  name: config
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: private_key
                  name: config
          image: us-east1-docker.pkg.dev/hifi-liquidator/hifi-liquidator-repo/hifi-liquidator:1.0.0
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
